In [2]:
import pandas as pd 
import numpy as np

In [3]:
con_matrix = np.load('con_matrix.npy')
dist_matrix = pd.read_csv('dist_matrix_time.csv').to_numpy()
con_matrix.shape
dist_matrix

array([[0., 1., 1., ..., 1., 2., 3.],
       [1., 0., 1., ..., 1., 2., 3.],
       [1., 1., 0., ..., 1., 2., 3.],
       ...,
       [1., 1., 1., ..., 0., 2., 3.],
       [2., 2., 2., ..., 2., 0., 4.],
       [3., 3., 3., ..., 3., 4., 0.]])

In [4]:
con_matrix[0,72,:]

array([367.80923663, 173.42212895, 128.970165  , 110.55863401,
       100.73233974,  94.69007035,  90.62327065,  87.70940127,
        85.52378754,  83.8261559 ,  82.47081057,  81.36447402])

In [5]:
#make the third dimention the same value as the first element in the third dimention
con_matrix_2 = con_matrix.copy()
for i in range(con_matrix.shape[0]):
    for j in range(con_matrix.shape[1]):
        mini  = dist_matrix[i,j].astype(int) 
        for k in range(con_matrix.shape[2]):
            con_matrix_2[i,j,k] = con_matrix[i,j,mini]


In [6]:
con_matrix_2[0,72,:]

array([110.55863401, 110.55863401, 110.55863401, 110.55863401,
       110.55863401, 110.55863401, 110.55863401, 110.55863401,
       110.55863401, 110.55863401, 110.55863401, 110.55863401])

In [7]:
#save the new matrix
np.save('con_matrix_noconsumptionsavings.npy',con_matrix_2)